openapi: 3.0.1
info:
  title: management-api
  description: REST API documentation for the management-api
  version: 0.6.3-SNAPSHOT
servers:
- url: /
paths:
  /federatedcatalog:
    post:
      tags:
      - Federated Catalog
      description: Obtains all Catalog currently held by this cache instance
      operationId: getCachedCatalog
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FederatedCatalogCacheQuery"
      responses:
        "200":
          description: "A list of Catalog is returned, potentially empty"
          content:
            application/json:
              schema:
                type: array
                example: null
                items:
                  $ref: "#/components/schemas/ContractOffer"
        "500":
          description: A Query could not be completed due to an internal error
components:
  schemas:
    Action:
      type: object
      properties:
        constraint:
          $ref: "#/components/schemas/Constraint"
        includedIn:
          type: string
          example: null
        type:
          type: string
          example: null
      example: null
    Constraint:
      required:
      - edctype
      type: object
      properties:
        edctype:
          type: string
          example: null
      example: null
      discriminator:
        propertyName: edctype
    ContractOffer:
      type: object
      properties:
        assetId:
          type: string
          example: null
        id:
          type: string
          example: null
        policy:
          $ref: "#/components/schemas/Policy"
      example: null
    Criterion:
      type: object
      properties:
        operandLeft:
          type: object
          example: null
        operandRight:
          type: object
          example: null
        operator:
          type: string
          example: null
      example: null
    Duty:
      type: object
      properties:
        action:
          $ref: "#/components/schemas/Action"
        constraints:
          type: array
          example: null
          items:
            $ref: "#/components/schemas/Constraint"
        parentPermission:
          $ref: "#/components/schemas/Permission"
      example: null
    FederatedCatalogCacheQuery:
      type: object
      properties:
        criteria:
          type: array
          example: null
          items:
            $ref: "#/components/schemas/Criterion"
      example: null
    JsonArray:
      type: array
      properties:
        empty:
          type: boolean
          example: null
        valueType:
          type: string
          example: null
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
      example: null
      items:
        $ref: "#/components/schemas/JsonValue"
    JsonValue:
      type: object
      properties:
        valueType:
          type: string
          example: null
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
      example: null
    Permission:
      type: object
      properties:
        action:
          $ref: "#/components/schemas/Action"
        constraints:
          type: array
          example: null
          items:
            $ref: "#/components/schemas/Constraint"
        duties:
          type: array
          example: null
          items:
            $ref: "#/components/schemas/Duty"
      example: null
    Policy:
      type: object
      properties:
        '@type':
          type: string
          example: null
          enum:
          - SET
          - OFFER
          - CONTRACT
        assignee:
          type: string
          example: null
        assigner:
          type: string
          example: null
        extensibleProperties:
          type: object
          additionalProperties:
            type: object
            example: null
          example: null
        inheritsFrom:
          type: string
          example: null
        obligations:
          type: array
          example: null
          items:
            $ref: "#/components/schemas/Duty"
        permissions:
          type: array
          example: null
          items:
            $ref: "#/components/schemas/Permission"
        prohibitions:
          type: array
          example: null
          items:
            $ref: "#/components/schemas/Prohibition"
        target:
          type: string
          example: null
      example: null
    Prohibition:
      type: object
      properties:
        action:
          $ref: "#/components/schemas/Action"
        constraints:
          type: array
          example: null
          items:
            $ref: "#/components/schemas/Constraint"
        remedies:
          type: array
          example: null
          items:
            $ref: "#/components/schemas/Duty"
      example: null
